apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" .}}-headless
  labels:
    app: {{ .Values.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: 8108
      targetPort: 8108
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense.fullname" .}}
spec:
  selector:
    app: {{ include "typesense.fullname" .}}
  type: NodePort
  ports:
  - name: http
    port: 8108
    targetPort: 8108